CREATE TABLE IF NOT EXISTS public.jobs (
id uuid DEFAULT gen_random_uuid(),
date bigint not null,
ownerEmail text not null,
company text not null,
title text not null,
description text not null,
externalUrl text not null,
remote boolean not null default false,
location text not null,
salaryLo integer,
salaryHi integer,
currency text,
country text,
tags text[],
image text,
seniority text,
other text,
active boolean not null default false
);

alter table jobs add constraint pk_jobs PRIMARY KEY(id);

INSERT INTO JOBS(
    id,
    date,
    ownerEmail,
    company,
    title,
    description,
    externalUrl,
    remote,
    location,
    salaryLo,
    salaryHi,
    currency,
    country,
    tags,
    image,
    seniority,
    other,
    active
) VALUES(
'843df718-ec6e-4d49-9289-f799c0f40064',
    1659186086,
    'daniel@rockthejvm.com',
      'Awesome Company',
      'Tech Lead',
      'An awesome job in Berlin',
      'https://rockthejvm.com/awesomejob',
      false,
      'Berlin',
      2000,
      3000,
      'EUR',
      'Germany',
      ARRAY[ 'scala', 'scala-3', 'cats'],
      NULL,
      'Senior',
      NULL,
      false
);